model_params:
  control_dim: 1280
  drug_emb_dim: 256
  hidden_dim: 256
  num_layers: 3
  dropout: 0.05

train_params:
  num_epochs: 10
  batch_size: 512
  lr: 0.0001
  weight_decay: 0.001

dataset_params:
  sciplex_adata_path: "/home/victor/projects/dege-fm/data/sciplex/sciplex_preprocessed.h5ad"
  zhao_adata_path: "/home/victor/projects/dege-fm/data/zhao/zhao_preprocessed.h5ad"
  sciplex_drugs_train: "/home/victor/projects/dege-fm/data/sciplex/drugs_train_list.txt"
  sciplex_drugs_test: "/home/victor/projects/dege-fm/data/sciplex/drugs_validation_list.txt"
  seed: 1702